# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:34:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class Status(Enum):
    ACCOUNT_LINK_STATUS_UNSPECIFIED = 'ACCOUNT_LINK_STATUS_UNSPECIFIED'
    ACCOUNT_LINK_STATUS_UNKNOWN = 'ACCOUNT_LINK_STATUS_UNKNOWN'
    REQUESTED_FROM_HOTEL_CENTER = 'REQUESTED_FROM_HOTEL_CENTER'
    REQUESTED_FROM_GOOGLE_ADS = 'REQUESTED_FROM_GOOGLE_ADS'
    APPROVED = 'APPROVED'


class DisplayNameState(Enum):
    REVIEW_STATE_UNSPECIFIED = 'REVIEW_STATE_UNSPECIFIED'
    REVIEW_STATE_NEW = 'REVIEW_STATE_NEW'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'


class IconDisapprovalReason(Enum):
    IMAGE_DISAPPROVAL_REASON_UNSPECIFIED = 'IMAGE_DISAPPROVAL_REASON_UNSPECIFIED'
    NOT_LIKE_SITE = 'NOT_LIKE_SITE'
    OFFENSIVE = 'OFFENSIVE'
    LOW_QUALITY = 'LOW_QUALITY'
    ANIMATED = 'ANIMATED'
    BAD_BACKGROUND = 'BAD_BACKGROUND'
    TEXT_TOO_SMALL = 'TEXT_TOO_SMALL'


class IconState(Enum):
    REVIEW_STATE_UNSPECIFIED = 'REVIEW_STATE_UNSPECIFIED'
    REVIEW_STATE_NEW = 'REVIEW_STATE_NEW'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'


class DataIssueSeverity(Enum):
    DATA_ISSUE_SEVERITY_UNSPECIFIED = 'DATA_ISSUE_SEVERITY_UNSPECIFIED'
    ERROR = 'ERROR'
    WARNING = 'WARNING'
    INFO = 'INFO'


class DataIssueType(Enum):
    FEED_DATA_ISSUE_UNSPECIFIED = 'FEED_DATA_ISSUE_UNSPECIFIED'
    FEED_DATA_ISSUE_UNKNOWN = 'FEED_DATA_ISSUE_UNKNOWN'
    NO_DATA_ISSUE = 'NO_DATA_ISSUE'
    DUPLICATE_ADDRESS = 'DUPLICATE_ADDRESS'
    MISSING_PHYSICAL_STREET_ADDRESS = 'MISSING_PHYSICAL_STREET_ADDRESS'
    MISSING_STREET_NAME = 'MISSING_STREET_NAME'
    MISSING_STREET_NUMBER = 'MISSING_STREET_NUMBER'
    MISSING_ADDRESS = 'MISSING_ADDRESS'
    MISSING_COUNTRY = 'MISSING_COUNTRY'
    INVALID_POSTAL_CODE = 'INVALID_POSTAL_CODE'
    INVALID_POSTAL_CODE_SUFFIX = 'INVALID_POSTAL_CODE_SUFFIX'
    UNEXPECTED_POSTAL_CODE_SUFFIX = 'UNEXPECTED_POSTAL_CODE_SUFFIX'
    UNEXPECTED_POSTAL_CODE = 'UNEXPECTED_POSTAL_CODE'
    INVALID_AMENITIES = 'INVALID_AMENITIES'
    INVALID_EMAIL_ADDRESS = 'INVALID_EMAIL_ADDRESS'
    DUPLICATE_LATLONG = 'DUPLICATE_LATLONG'
    LATLONG_INCONSISTENT_WITH_ADDRESS = 'LATLONG_INCONSISTENT_WITH_ADDRESS'
    MISSING_LATLONG = 'MISSING_LATLONG'
    COULD_NOT_GEOCODE = 'COULD_NOT_GEOCODE'
    MISSING_HOTEL_NAME = 'MISSING_HOTEL_NAME'
    HOTEL_NAME_EMPTY = 'HOTEL_NAME_EMPTY'
    INVALID_HOTEL_NAME = 'INVALID_HOTEL_NAME'
    HOTEL_NAME_TOO_LONG = 'HOTEL_NAME_TOO_LONG'
    PARSE_ERROR_IN_XML = 'PARSE_ERROR_IN_XML'
    UNEXPECTED_ATTRIBUTE_IN_XML = 'UNEXPECTED_ATTRIBUTE_IN_XML'
    DUPLICATE_PHONE_NUMBER = 'DUPLICATE_PHONE_NUMBER'
    MISSING_PHONE_NUMBER = 'MISSING_PHONE_NUMBER'
    MISSING_VOICE_PHONE_NUMBER = 'MISSING_VOICE_PHONE_NUMBER'
    INVALID_PHONE_NUMBER_FORMAT = 'INVALID_PHONE_NUMBER_FORMAT'
    INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER'
    INVALID_PHONE_NUMBER_COUNTRY_CODE = 'INVALID_PHONE_NUMBER_COUNTRY_CODE'
    PHONE_NUMBER_TOO_LONG = 'PHONE_NUMBER_TOO_LONG'
    PHONE_NUMBER_TOO_SHORT = 'PHONE_NUMBER_TOO_SHORT'
    INVALID_WEBSITE_URL = 'INVALID_WEBSITE_URL'
    ADWORDS_ATTRIBUTE_TOO_LONG = 'ADWORDS_ATTRIBUTE_TOO_LONG'
    BRAND_NOT_ALLOWED = 'BRAND_NOT_ALLOWED'
    FLAGGED_DUE_TO_SUSPICIOUS_METADATA = 'FLAGGED_DUE_TO_SUSPICIOUS_METADATA'
    NOT_ENOUGH_IMAGES_PROVIDED = 'NOT_ENOUGH_IMAGES_PROVIDED'
    IMAGE_PROCESSING_IN_PROGRESS = 'IMAGE_PROCESSING_IN_PROGRESS'
    CANNOT_FETCH_IMAGES = 'CANNOT_FETCH_IMAGES'
    INCOMPATIBLE_IMAGE_SIZE_OR_LOW_QUALITY = 'INCOMPATIBLE_IMAGE_SIZE_OR_LOW_QUALITY'
    MISSING_LANG_IN_RAW_LISTING = 'MISSING_LANG_IN_RAW_LISTING'
    IS_HOTEL = 'IS_HOTEL'
    MISSING_REQ_ATTR = 'MISSING_REQ_ATTR'
    MISSING_NAME = 'MISSING_NAME'
    MISSING_LANG_IN_NAME = 'MISSING_LANG_IN_NAME'
    VR_NAME_TOO_LONG = 'VR_NAME_TOO_LONG'
    TEST_PROPERTY = 'TEST_PROPERTY'
    NON_VR_ACCOMMODATION_TYPE_BASED_ON_LISTING_NAME = (
        'NON_VR_ACCOMMODATION_TYPE_BASED_ON_LISTING_NAME'
    )
    BRAND_NAME_TOO_LONG = 'BRAND_NAME_TOO_LONG'
    MISSING_BRAND_NAME = 'MISSING_BRAND_NAME'
    INVALID_REVIEW_RATING = 'INVALID_REVIEW_RATING'
    INVALID_CHECKIN_FORMAT = 'INVALID_CHECKIN_FORMAT'
    INVALID_CHECKOUT_FORMAT = 'INVALID_CHECKOUT_FORMAT'


class DataIssueDetail(BaseModel):
    dataIssueSeverity: Optional[DataIssueSeverity] = Field(
        None, description='The severity of the data issue.'
    )
    dataIssueType: Optional[DataIssueType] = Field(
        None, description='The type of the data issue.'
    )
    isSelfResolving: Optional[bool] = Field(
        None,
        description='Whether or not the issue is self-resolving. If true, the issue is expected to resolve itself. If false or not set, action is needed to resolve the issue. Refer to documentation on the data issue’s type for further information.',
    )


class Date(BaseModel):
    day: Optional[int] = Field(
        None,
        description="Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
    )
    month: Optional[int] = Field(
        None,
        description='Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.',
    )
    year: Optional[int] = Field(
        None,
        description='Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.',
    )


class DisapprovalReason(Enum):
    DISAPPROVAL_REASON_UNSPECIFIED = 'DISAPPROVAL_REASON_UNSPECIFIED'
    PUNCTUATION = 'PUNCTUATION'
    MARKETING_LANGUAGE = 'MARKETING_LANGUAGE'
    LANDING_PAGE_NOT_MATCHED = 'LANDING_PAGE_NOT_MATCHED'


class DisplayNameDisapprovalReason(BaseModel):
    disapprovalReason: Optional[DisapprovalReason] = Field(
        None, description='Disapproval reason.'
    )
    languageCode: Optional[str] = Field(
        None, description='Language of the disapproved display name.'
    )


class Empty(BaseModel):
    pass


class DeviceType(Enum):
    DEVICE_UNSPECIFIED = 'DEVICE_UNSPECIFIED'
    DEVICE_UNKNOWN = 'DEVICE_UNKNOWN'
    DESKTOP = 'DESKTOP'
    MOBILE = 'MOBILE'
    TABLET = 'TABLET'


class FreeBookingLinksResult(BaseModel):
    clickCount: Optional[str] = Field(
        None,
        description='The total number of clicks that were recorded for this result.',
    )
    date: Optional[Date] = Field(
        None,
        description='A date within the requested date range. Only present if `date` is specified in `aggregateBy` in the request.',
    )
    deviceType: Optional[DeviceType] = Field(
        None,
        description='The user’s device type. Only present if `deviceType` is specified in `aggregateBy` in the request.',
    )
    partnerHotelDisplayName: Optional[str] = Field(
        None,
        description="Partner's hotel name. Only present if `partnerHotelDisplayName` is specified in `aggregateBy` in the request.",
    )
    partnerHotelId: Optional[str] = Field(
        None,
        description="Partner's hotel ID. Only present if `partnerHotelId` is specified in `aggregateBy` in the request.",
    )
    userRegionCode: Optional[str] = Field(
        None,
        description='ISO 3116 region code of the country/region of the user. Only present if `userRegionCode` is specified in `aggregateBy` in the request',
    )


class HotelList(BaseModel):
    partnerHotelIds: Optional[List[str]] = Field(None, description='Hotel IDs.')


class HotelPricePerItinerary(BaseModel):
    checkinDate: Optional[Date] = Field(None, description='Check-in date.')
    currencyCode: Optional[str] = Field(
        None, description='Currency for `price`, `taxes`, and `fees`.'
    )
    fees: Optional[float] = Field(None, description='Fees for this itinerary.')
    lengthOfStayDays: Optional[int] = Field(
        None, description='Number of nights for the itinerary.'
    )
    price: Optional[float] = Field(None, description='Hotel price for this itinerary.')
    taxes: Optional[float] = Field(None, description='Taxes for this itinerary.')
    updateTime: Optional[str] = Field(
        None, description='Update timestamp for this hotel price.'
    )


class DataIssue(Enum):
    FEED_DATA_ISSUE_UNSPECIFIED = 'FEED_DATA_ISSUE_UNSPECIFIED'
    FEED_DATA_ISSUE_UNKNOWN = 'FEED_DATA_ISSUE_UNKNOWN'
    NO_DATA_ISSUE = 'NO_DATA_ISSUE'
    DUPLICATE_ADDRESS = 'DUPLICATE_ADDRESS'
    MISSING_PHYSICAL_STREET_ADDRESS = 'MISSING_PHYSICAL_STREET_ADDRESS'
    MISSING_STREET_NAME = 'MISSING_STREET_NAME'
    MISSING_STREET_NUMBER = 'MISSING_STREET_NUMBER'
    MISSING_ADDRESS = 'MISSING_ADDRESS'
    MISSING_COUNTRY = 'MISSING_COUNTRY'
    INVALID_POSTAL_CODE = 'INVALID_POSTAL_CODE'
    INVALID_POSTAL_CODE_SUFFIX = 'INVALID_POSTAL_CODE_SUFFIX'
    UNEXPECTED_POSTAL_CODE_SUFFIX = 'UNEXPECTED_POSTAL_CODE_SUFFIX'
    UNEXPECTED_POSTAL_CODE = 'UNEXPECTED_POSTAL_CODE'
    INVALID_AMENITIES = 'INVALID_AMENITIES'
    INVALID_EMAIL_ADDRESS = 'INVALID_EMAIL_ADDRESS'
    DUPLICATE_LATLONG = 'DUPLICATE_LATLONG'
    LATLONG_INCONSISTENT_WITH_ADDRESS = 'LATLONG_INCONSISTENT_WITH_ADDRESS'
    MISSING_LATLONG = 'MISSING_LATLONG'
    COULD_NOT_GEOCODE = 'COULD_NOT_GEOCODE'
    MISSING_HOTEL_NAME = 'MISSING_HOTEL_NAME'
    HOTEL_NAME_EMPTY = 'HOTEL_NAME_EMPTY'
    INVALID_HOTEL_NAME = 'INVALID_HOTEL_NAME'
    HOTEL_NAME_TOO_LONG = 'HOTEL_NAME_TOO_LONG'
    PARSE_ERROR_IN_XML = 'PARSE_ERROR_IN_XML'
    UNEXPECTED_ATTRIBUTE_IN_XML = 'UNEXPECTED_ATTRIBUTE_IN_XML'
    DUPLICATE_PHONE_NUMBER = 'DUPLICATE_PHONE_NUMBER'
    MISSING_PHONE_NUMBER = 'MISSING_PHONE_NUMBER'
    MISSING_VOICE_PHONE_NUMBER = 'MISSING_VOICE_PHONE_NUMBER'
    INVALID_PHONE_NUMBER_FORMAT = 'INVALID_PHONE_NUMBER_FORMAT'
    INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER'
    INVALID_PHONE_NUMBER_COUNTRY_CODE = 'INVALID_PHONE_NUMBER_COUNTRY_CODE'
    PHONE_NUMBER_TOO_LONG = 'PHONE_NUMBER_TOO_LONG'
    PHONE_NUMBER_TOO_SHORT = 'PHONE_NUMBER_TOO_SHORT'
    INVALID_WEBSITE_URL = 'INVALID_WEBSITE_URL'
    ADWORDS_ATTRIBUTE_TOO_LONG = 'ADWORDS_ATTRIBUTE_TOO_LONG'
    BRAND_NOT_ALLOWED = 'BRAND_NOT_ALLOWED'
    FLAGGED_DUE_TO_SUSPICIOUS_METADATA = 'FLAGGED_DUE_TO_SUSPICIOUS_METADATA'
    NOT_ENOUGH_IMAGES_PROVIDED = 'NOT_ENOUGH_IMAGES_PROVIDED'
    IMAGE_PROCESSING_IN_PROGRESS = 'IMAGE_PROCESSING_IN_PROGRESS'
    CANNOT_FETCH_IMAGES = 'CANNOT_FETCH_IMAGES'
    INCOMPATIBLE_IMAGE_SIZE_OR_LOW_QUALITY = 'INCOMPATIBLE_IMAGE_SIZE_OR_LOW_QUALITY'
    MISSING_LANG_IN_RAW_LISTING = 'MISSING_LANG_IN_RAW_LISTING'
    IS_HOTEL = 'IS_HOTEL'
    MISSING_REQ_ATTR = 'MISSING_REQ_ATTR'
    MISSING_NAME = 'MISSING_NAME'
    MISSING_LANG_IN_NAME = 'MISSING_LANG_IN_NAME'
    VR_NAME_TOO_LONG = 'VR_NAME_TOO_LONG'
    TEST_PROPERTY = 'TEST_PROPERTY'
    NON_VR_ACCOMMODATION_TYPE_BASED_ON_LISTING_NAME = (
        'NON_VR_ACCOMMODATION_TYPE_BASED_ON_LISTING_NAME'
    )
    BRAND_NAME_TOO_LONG = 'BRAND_NAME_TOO_LONG'
    MISSING_BRAND_NAME = 'MISSING_BRAND_NAME'
    INVALID_REVIEW_RATING = 'INVALID_REVIEW_RATING'
    INVALID_CHECKIN_FORMAT = 'INVALID_CHECKIN_FORMAT'
    INVALID_CHECKOUT_FORMAT = 'INVALID_CHECKOUT_FORMAT'


class MatchStatus(Enum):
    MATCH_STATUS_UNSPECIFIED = 'MATCH_STATUS_UNSPECIFIED'
    MATCH_STATUS_UNKNOWN = 'MATCH_STATUS_UNKNOWN'
    NOT_MATCHED = 'NOT_MATCHED'
    MATCHED = 'MATCHED'
    MAP_OVERLAP = 'MAP_OVERLAP'


class HotelView(BaseModel):
    dataIssueDetail: Optional[List[DataIssueDetail]] = Field(
        None,
        description='The type and severity of each data quality issue in the feed. If your feed contains data issues, update the feed and resubmit it. For more information, refer to this article.',
    )
    dataIssues: Optional[List[DataIssue]] = Field(
        None,
        description='DEPRECATED. Indicates that the hotel has data quality issues. The value of this field indicates the type of error. This has been replaced with the data_issue_detail field. If your feed contains data issues, update the feed and resubmit it. For more information, refer to this article.',
    )
    googleClusterId: Optional[str] = Field(
        None, description='The Google Maps identifier for the hotel.'
    )
    googleHotelDisplayName: Optional[str] = Field(
        None, description="Google's hotel name."
    )
    googleHotelId: Optional[str] = Field(
        None, description="Google's canonical ID for the hotel."
    )
    liveOnGoogle: Optional[bool] = Field(
        None,
        description="Optional. Whether the hotel appears in Google's hotel booking links. Declaration & behavior to get detection of presence/absence in JSON conversion.",
    )
    matchStatus: Optional[MatchStatus] = Field(
        None, description='Current matching status of the hotel.'
    )
    overclusteredPartnerHotelIds: Optional[List[str]] = Field(
        None,
        description='Other hotels with which the hotel is overclustered. If your feed contains overclustered hotels, update the feed and resubmit it. To do this, you can use the manual match tool.',
    )
    partnerHotelDisplayName: Optional[str] = Field(
        None, description="Partner's hotel name."
    )
    partnerHotelId: Optional[str] = Field(
        None,
        description='The unique ID of the hotel that the partner provides in their Hotel List Feed.',
    )
    primaryOverclusteredPartnerHotelId: Optional[str] = Field(
        None, description='The primary hotel in the overclustered set.'
    )
    propertyDetails: Optional[str] = Field(
        None,
        description='Optional. A URL to the property on Google. Only available for properties that are listed.',
    )


class DisapprovalReason1(Enum):
    IMAGE_DISAPPROVAL_REASON_UNSPECIFIED = 'IMAGE_DISAPPROVAL_REASON_UNSPECIFIED'
    NOT_LIKE_SITE = 'NOT_LIKE_SITE'
    OFFENSIVE = 'OFFENSIVE'
    LOW_QUALITY = 'LOW_QUALITY'
    ANIMATED = 'ANIMATED'
    BAD_BACKGROUND = 'BAD_BACKGROUND'
    TEXT_TOO_SMALL = 'TEXT_TOO_SMALL'


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    NEW = 'NEW'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'


class Icon(BaseModel):
    disapprovalReasons: Optional[List[DisapprovalReason1]] = Field(
        None,
        description="Output only. The icon's disapproval reason(s). Only applies to icons with `REJECTED` state.",
    )
    iconUri: Optional[str] = Field(
        None,
        description="Output only. The approved icon's Google-hosted URI. Only applies to icons with `APPROVED` state.",
    )
    imageData: Optional[str] = Field(
        None,
        description='Required. Input only. The icon contents, which must be in PNG format, or convertible to PNG.',
    )
    name: Optional[str] = Field(
        None,
        description='Required. Output only. The resource name for the icon in the format `accounts/{account_id}/icons/{icon_id}`. Google generates the `icon_id` during the `create` operation. Use the `icon_id` to associate the icon with a brand using the [accounts.brands](/hotels/hotel-prices/api-reference/rest/v3/accounts.brands#resource:-brand) API.',
    )
    reference: Optional[str] = Field(
        None,
        description="Optional. Value for tracking the icon. It could be the primary key to your icon in your system, or the icon's filename. Google does not use this value.",
    )
    state: Optional[State] = Field(
        None, description="Output only. The icon's current state."
    )


class Key(BaseModel):
    advanceBookingWindow: Optional[int] = Field(
        None,
        description='The number of days in advance the user wants to book the itinerary. If `advanceBookingWindow` is not a value of the `aggregateBy` parameter in the request call, then the `advanceBookingWindow` field is not returned in the `Key`.',
    )
    checkinDate: Optional[Date] = Field(
        None,
        description='The check-in date of the itinerary. If `checkinDate` is not a value of the `aggregateBy` parameter in the request call, then the `checkinDate` field is not returned in the `Key`.',
    )
    date: Optional[Date] = Field(
        None,
        description='The date for which you are requesting metrics. If `date` is not a value of the `aggregateBy` parameter in the request call, then the `date` field is not returned in the `Key`.',
    )
    deviceType: Optional[DeviceType] = Field(
        None,
        description='The user’s device type. If `deviceType` is not a value of the `aggregateBy` parameter in the request call, then the `deviceType` field is not returned in the `Key`.',
    )
    hotelRegionCode: Optional[str] = Field(
        None,
        description='CLDR region code of the country/region of the hotel. If `hotelRegionCode` is not a value of the `aggregateBy` parameter in the request call, then the `hotelRegionCode` field is not returned in the `Key`.',
    )
    lengthOfStayDays: Optional[int] = Field(
        None,
        description='The number of nights for the itinerary. If `lengthOfStayDays` is not a value of the `aggregateBy` parameter in the request call, then the `lengthOfStayDays` field is not returned in the `Key`.',
    )
    occupancy: Optional[int] = Field(
        None,
        description='The total occupancy of the itinerary. If `occupancy` is not a value of the `aggregateBy` parameter in the request call, then the `occupancy` field is not returned in the `Key`.',
    )
    partnerHotelId: Optional[str] = Field(
        None,
        description="Partner's hotel ID. If `partnerHotelId` is not a value of the `aggregateBy` parameter in the request call, then the `partnerHotelId` field is not returned in the `Key`.",
    )
    userRegionCode: Optional[str] = Field(
        None,
        description='ISO 3116 region code of the country/region of the user. If `userRegionCode` is not a value of the `aggregateBy` parameter in the request call, then the `userRegionCode` field is not returned in the `Key`.',
    )


class LatLng(BaseModel):
    latitude: Optional[float] = Field(
        None,
        description='The latitude in degrees. It must be in the range [-90.0, +90.0].',
    )
    longitude: Optional[float] = Field(
        None,
        description='The longitude in degrees. It must be in the range [-180.0, +180.0].',
    )


class ListHotelViewsResponse(BaseModel):
    hotelViews: Optional[List[HotelView]] = Field(
        None, description='The list of rows that match the query.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Pagination token used to retrieve the next page of results.'
    )


class ListIconsResponse(BaseModel):
    icons: Optional[List[Icon]] = Field(
        None,
        description='A list of all icons associated with the queried partner account.',
    )


class LocalizedText(BaseModel):
    languageCode: Optional[str] = Field(
        None,
        description='The text\'s BCP-47 language code, such as "en-US" or "sr-Latn". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.',
    )
    text: Optional[str] = Field(
        None,
        description="Localized string in the language corresponding to `language_code' below.",
    )


class NoPriceCountDetails(BaseModel):
    livePricingConfigIssueCount: Optional[str] = Field(
        None,
        description="The total number of missed participation due to live pricing not being triggered for any of the following reasons: * You didn't have live pricing configured for these searches. * You restricted Google from accessing the hotel itinerary in question.",
    )
    livePricingNotAvailableCount: Optional[str] = Field(
        None,
        description='The total number of missed participation due to live pricing being unavailable. Live pricing will not be triggered for certain default itineraries or UIs. In this scenario, partners will need a cached price to participate.',
    )
    livePricingNotTriggeredCount: Optional[str] = Field(
        None,
        description="The total number of missed participation due to live pricing not being triggered for any of the following reasons: * You didn't set a bid. * You didn't have a valid landing page. * There weren't enough prices in the cache.",
    )
    livePricingOtherReasonCount: Optional[str] = Field(
        None,
        description='The number of missed participations due to other issues with live pricing.',
    )
    livePricingTechnicalIssueCount: Optional[str] = Field(
        None,
        description='The total number of missed participation due to technical issues with live pricing for any of the following reasons: * You didn’t respond quickly enough and exceeded the response deadline (around 4000 milliseconds). * You returned an error. * Your response was malformed.',
    )


class MismatchReason(Enum):
    MISMATCH_REASON_UNSPECIFIED = 'MISMATCH_REASON_UNSPECIFIED'
    MISMATCH_REASON_UNKNOWN = 'MISMATCH_REASON_UNKNOWN'
    TAX_MISMATCH = 'TAX_MISMATCH'
    ROOM_UNAVAILABLE = 'ROOM_UNAVAILABLE'
    SITE_ERROR = 'SITE_ERROR'
    PRICE_FEED_DELAYED = 'PRICE_FEED_DELAYED'
    DISCOUNT_MISSING = 'DISCOUNT_MISSING'
    INCORRECT_DISCOUNT_VALUE = 'INCORRECT_DISCOUNT_VALUE'
    WRONG_ITINERARY = 'WRONG_ITINERARY'


class SignalSource(Enum):
    SIGNAL_SOURCE_UNSPECIFIED = 'SIGNAL_SOURCE_UNSPECIFIED'
    SIGNAL_SOURCE_UNKNOWN = 'SIGNAL_SOURCE_UNKNOWN'
    FETCHED = 'FETCHED'
    PIXEL = 'PIXEL'


class AdvanceBookingWindowRange(Enum):
    ADVANCE_BOOKING_WINDOW_RANGE_UNSPECIFIED = (
        'ADVANCE_BOOKING_WINDOW_RANGE_UNSPECIFIED'
    )
    ADVANCE_BOOKING_WINDOW_RANGE_UNKNOWN = 'ADVANCE_BOOKING_WINDOW_RANGE_UNKNOWN'
    DAYS_0_TO_30 = 'DAYS_0_TO_30'
    DAYS_31_TO_60 = 'DAYS_31_TO_60'
    DAYS_61_TO_90 = 'DAYS_61_TO_90'
    DAYS_91_TO_120 = 'DAYS_91_TO_120'
    DAYS_121_TO_150 = 'DAYS_121_TO_150'
    DAYS_151_TO_180 = 'DAYS_151_TO_180'
    DAYS_181_TO_210 = 'DAYS_181_TO_210'
    DAYS_211_TO_240 = 'DAYS_211_TO_240'
    DAYS_241_TO_270 = 'DAYS_241_TO_270'
    DAYS_271_TO_300 = 'DAYS_271_TO_300'
    DAYS_301_TO_330 = 'DAYS_301_TO_330'


class LengthOfStayRange(Enum):
    LENGTH_OF_STAY_RANGE_UNSPECIFIED = 'LENGTH_OF_STAY_RANGE_UNSPECIFIED'
    LENGTH_OF_STAY_RANGE_UNKNOWN = 'LENGTH_OF_STAY_RANGE_UNKNOWN'
    LENGTH_OF_STAY_1_TO_7 = 'LENGTH_OF_STAY_1_TO_7'
    LENGTH_OF_STAY_8_TO_14 = 'LENGTH_OF_STAY_8_TO_14'
    LENGTH_OF_STAY_15_TO_30 = 'LENGTH_OF_STAY_15_TO_30'


class PriceCoverageBucket(BaseModel):
    advanceBookingWindowRange: Optional[AdvanceBookingWindowRange] = Field(
        None, description='Advance booking window range.'
    )
    availablePriceCount: Optional[str] = Field(
        None,
        description='Number of prices for this advance booking window bucket and length of stay bucket.',
    )
    lengthOfStayRange: Optional[LengthOfStayRange] = Field(
        None, description='Length of stay range.'
    )
    priceCoveragePercent: Optional[float] = Field(
        None,
        description='The percent of itineraries for which you have coverage for this advance booking window bucket and length of stay bucket.',
    )


class PriceCoverageView(BaseModel):
    calculationDate: Optional[Date] = Field(
        None, description='The date on which the calculations were made.'
    )
    matchedPropertyCount: Optional[int] = Field(
        None,
        description='The total number of properties that have prices for the given itineraries.',
    )
    priceCoverageBinaryPercent: Optional[float] = Field(
        None,
        description='The ratio between the number of hotels which have at least one price for the calculation period and `matched_property_count`.',
    )
    priceCoverageBuckets: Optional[List[PriceCoverageBucket]] = Field(
        None,
        description='Price coverage stats for combinations of advance booking window and length of stay ranges.',
    )
    priceCoveragePercent: Optional[float] = Field(
        None,
        description='The overall price coverage for an account. This value is the ratio between the number of hotel prices for the calculation booking window and length of stay range divided by the number of all possible prices, which is `matched_property_count` times 330 (for advance book window) times 30 (for length of stay).',
    )


class PriceMissingCountDetails(BaseModel):
    bandwidthDepletedCount: Optional[str] = Field(
        None,
        description='No price was cached for this itinerary, and there was no live query quota remaining.',
    )
    cacheRateMissingCount: Optional[str] = Field(
        None,
        description='No price exists in the cache for this itinerary. A live query was not done due to page constraints.',
    )
    itineraryBlockedCount: Optional[str] = Field(
        None,
        description='The itinerary was outside of your basic parameters, so no price was pulled for the itinerary from either live query or cache fill.',
    )
    livePricingErrorCount: Optional[str] = Field(
        None,
        description='No price was cached for this itinerary. A live query did not time out, but your system returned an error.',
    )
    livePricingNotSetupCount: Optional[str] = Field(
        None,
        description='No price was cached for this itinerary, and live query was not configured for this account.',
    )
    livePricingTimeoutCount: Optional[str] = Field(
        None,
        description='No price was cached for this itinerary, and a live query sent to your system timed out.',
    )


class PriceProblemCountDetails(BaseModel):
    hotelSuspendedCount: Optional[str] = Field(
        None,
        description='The hotel was suspended. This may be due to persistent problems in areas such as incorrect taxes and fees.',
    )
    priceUnusuallyHighCount: Optional[str] = Field(
        None,
        description='The price given for this itinerary seemed oddly high compared to regional trends.',
    )
    priceUnusuallyLowCount: Optional[str] = Field(
        None,
        description='The price given for this itinerary seemed oddly low compared to regional trends.',
    )
    taxesAndFeesMissingCount: Optional[str] = Field(
        None, description='Taxes and fees were missing from pricing.'
    )


class PriceRecord(BaseModel):
    basePrice: Optional[float] = Field(None, description='Base price.')
    currencyCode: Optional[str] = Field(None, description='ISO 4217 currency code.')
    taxesAndFees: Optional[float] = Field(None, description='Taxes and fees.')
    time: Optional[str] = Field(None, description='Timestamp of this price record.')


class PriceUnavailableCountDetails(BaseModel):
    participationNotLikelyCount: Optional[str] = Field(
        None,
        description='No price was cached for this itinerary, and no live query was done because your server usually tells us the hotel is unavailable or sold out.',
    )
    priceUnavailableCount: Optional[str] = Field(
        None,
        description="Hotel did not participate because it wasn't available for the itinerary dates.",
    )


class PriceView(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Resource name in the format `accounts/{account_id}/priceViews/{partner_hotel_id}`.',
    )
    perItineraryPrices: Optional[List[HotelPricePerItinerary]] = Field(
        None, description='Price for each itinerary.'
    )


class AdvanceBookingWindow(Enum):
    ADVANCE_BOOKING_WINDOW_UNSPECIFIED = 'ADVANCE_BOOKING_WINDOW_UNSPECIFIED'
    ADVANCE_BOOKING_WINDOW_SAME_DAY = 'ADVANCE_BOOKING_WINDOW_SAME_DAY'
    ADVANCE_BOOKING_WINDOW_NEXT_DAY = 'ADVANCE_BOOKING_WINDOW_NEXT_DAY'
    ADVANCE_BOOKING_WINDOW_DAYS_2_TO_7 = 'ADVANCE_BOOKING_WINDOW_DAYS_2_TO_7'
    ADVANCE_BOOKING_WINDOW_DAYS_8_TO_14 = 'ADVANCE_BOOKING_WINDOW_DAYS_8_TO_14'
    ADVANCE_BOOKING_WINDOW_DAYS_15_TO_30 = 'ADVANCE_BOOKING_WINDOW_DAYS_15_TO_30'
    ADVANCE_BOOKING_WINDOW_DAYS_31_TO_60 = 'ADVANCE_BOOKING_WINDOW_DAYS_31_TO_60'
    ADVANCE_BOOKING_WINDOW_DAYS_61_TO_90 = 'ADVANCE_BOOKING_WINDOW_DAYS_61_TO_90'
    ADVANCE_BOOKING_WINDOW_DAYS_91_TO_120 = 'ADVANCE_BOOKING_WINDOW_DAYS_91_TO_120'
    ADVANCE_BOOKING_WINDOW_DAYS_121_TO_150 = 'ADVANCE_BOOKING_WINDOW_DAYS_121_TO_150'
    ADVANCE_BOOKING_WINDOW_DAYS_151_TO_180 = 'ADVANCE_BOOKING_WINDOW_DAYS_151_TO_180'
    ADVANCE_BOOKING_WINDOW_DAYS_OVER_180 = 'ADVANCE_BOOKING_WINDOW_DAYS_OVER_180'


class LengthOfStay(Enum):
    LENGTH_OF_STAY_UNSPECIFIED = 'LENGTH_OF_STAY_UNSPECIFIED'
    LENGTH_OF_STAY_NIGHTS_1 = 'LENGTH_OF_STAY_NIGHTS_1'
    LENGTH_OF_STAY_NIGHTS_2 = 'LENGTH_OF_STAY_NIGHTS_2'
    LENGTH_OF_STAY_NIGHTS_3 = 'LENGTH_OF_STAY_NIGHTS_3'
    LENGTH_OF_STAY_NIGHTS_4_TO_7 = 'LENGTH_OF_STAY_NIGHTS_4_TO_7'
    LENGTH_OF_STAY_NIGHTS_8_TO_14 = 'LENGTH_OF_STAY_NIGHTS_8_TO_14'
    LENGTH_OF_STAY_NIGHTS_15_TO_21 = 'LENGTH_OF_STAY_NIGHTS_15_TO_21'
    LENGTH_OF_STAY_NIGHTS_22_TO_30 = 'LENGTH_OF_STAY_NIGHTS_22_TO_30'
    LENGTH_OF_STAY_NIGHTS_OVER_30 = 'LENGTH_OF_STAY_NIGHTS_OVER_30'


class Occupancy(Enum):
    OCCUPANCY_UNSPECIFIED = 'OCCUPANCY_UNSPECIFIED'
    OCCUPANCY_1 = 'OCCUPANCY_1'
    OCCUPANCY_2 = 'OCCUPANCY_2'
    OCCUPANCY_3 = 'OCCUPANCY_3'
    OCCUPANCY_4 = 'OCCUPANCY_4'
    OCCUPANCY_OVER_4 = 'OCCUPANCY_OVER_4'


class PropertyPerformanceResult(BaseModel):
    adsClickCount: Optional[str] = Field(
        None,
        description='The total number of ad clicks that were recorded for this result.',
    )
    adsClickthroughRate: Optional[float] = Field(
        None,
        description='Equal to `ads_click_count` divided by `ads_impression_count`.',
    )
    adsImpressionCount: Optional[str] = Field(
        None,
        description='The total number of ad impressions that were recorded for this result.',
    )
    advanceBookingWindow: Optional[AdvanceBookingWindow] = Field(
        None,
        description="Difference in days between query date and check-in date in property's local timezone. Only present if `advanceBookingWindow` is specified in `aggregateBy` in the request.",
    )
    brand: Optional[str] = Field(
        None,
        description='Partner-specified brand for the property. Only present if `brand` is specified in `aggregateBy` in the request.',
    )
    clickCount: Optional[str] = Field(
        None,
        description='The total number of free booking link clicks that were recorded for this result.',
    )
    clickthroughRate: Optional[float] = Field(
        None, description='Equal to `click_count` divided by `impression_count`.'
    )
    date: Optional[Date] = Field(
        None,
        description='A date within the requested date range. Only present if `date` is specified in `aggregateBy` in the request.',
    )
    deviceType: Optional[DeviceType] = Field(
        None,
        description='The user’s device type. Only present if `deviceType` is specified in `aggregateBy` in the request.',
    )
    highIntentUsers: Optional[bool] = Field(
        None,
        description='Whether the user’s query indicated a strong interest in booking. Only present if `highIntentUsers` is specified in `aggregateBy` in the request.',
    )
    impressionCount: Optional[str] = Field(
        None,
        description='The total number of free booking link impressions that were recorded for this result. This value is rounded to preserve user privacy.',
    )
    lengthOfStay: Optional[LengthOfStay] = Field(
        None,
        description='Number of nights between check-in and check-out dates specified by user. Only present if `lengthOfStay` is specified in `aggregateBy` in the request.',
    )
    occupancy: Optional[Occupancy] = Field(
        None,
        description='Requested number of people staying at the property. Only present if `partnerPropertyId` is specified in `aggregateBy` in the request.',
    )
    partnerPropertyDisplayName: Optional[str] = Field(
        None,
        description="Partner's property name. Only present if `partnerPropertyDisplayName` is specified in `aggregateBy` in the request.",
    )
    partnerPropertyId: Optional[str] = Field(
        None,
        description="Partner's property ID. Only present if `partnerPropertyId` is specified in `aggregateBy` in the request.",
    )
    propertyRegionCode: Optional[str] = Field(
        None,
        description='ISO 3116 region code of the country/region of the property. Only present if `propertyRegionCode` is specified in `aggregateBy` in the request',
    )
    userRegionCode: Optional[str] = Field(
        None,
        description='ISO 3116 region code of the country/region of the user. Only present if `userRegionCode` is specified in `aggregateBy` in the request',
    )


class QueryFreeBookingLinksReportResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='Pagination token used to retrieve the next page of results. If this field is omitted, there are no subsequent pages.',
    )
    results: Optional[List[FreeBookingLinksResult]] = Field(
        None, description='The list of results that match the query.'
    )


class QueryPropertyPerformanceReportResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='Pagination token used to retrieve the next page of results. If this field is omitted, there are no subsequent pages.',
    )
    results: Optional[List[PropertyPerformanceResult]] = Field(
        None, description='The list of results that match the query.'
    )


class Type(Enum):
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    OVERALL = 'OVERALL'


class Rating(BaseModel):
    ratingScale: Optional[int] = Field(None, description='Maximum rating possible.')
    score: Optional[float] = Field(None, description='The rating score. (e.g. 8.5)')
    type: Optional[Type] = Field(None, description='The type of the rating.')


class ReconciliationReport(BaseModel):
    contents: Optional[str] = Field(
        None,
        description='Required. The contents of the commission report. Report contents must conform to the requirements specified in [Reconciliation reports] (//support.google.com/hotelprices/answer/7019060#creating).',
    )
    fileName: Optional[str] = Field(
        None, description='Required. Desired filename of the reconciliation report.'
    )
    name: Optional[str] = Field(
        None,
        description='Resource name in the format `accounts/{account_id}/reconciliationReports/{datetime}~{filename}`. The value for `{datetime}` must be from 0001-01-01T00:00:00 to 9999-12-31T23:59:59 inclusive.',
    )


class ReconciliationReportValidationIssue(BaseModel):
    description: Optional[str] = Field(
        None,
        description='Text description of the issue, typically including what was seen and why it was invalid.',
    )
    fieldName: Optional[str] = Field(
        None,
        description='Name of the invalid field. If no field name is given, this issue applies to the whole line (or file).',
    )
    lineNum: Optional[int] = Field(
        None,
        description='The line number on which the issue was detected. If this field is 0, the issue applies to the whole file.',
    )


class Type1(Enum):
    UNKNOWN = 'UNKNOWN'
    EDITORIAL = 'EDITORIAL'
    USER = 'USER'


class Review(BaseModel):
    author: Optional[str] = Field(None, description='The author of the review.')
    body: Optional[str] = Field(None, description='The body of the review.')
    languageCode: Optional[str] = Field(
        None, description='Language of the review, such as "en", "de", etc.'
    )
    link: Optional[str] = Field(None, description='The url of the review.')
    rating: Optional[List[Rating]] = Field(
        None,
        description='Any ratings associated with this review. This is repeated because reviews can include ratings on different aspects of a listing, e.g. location, cleanliness, etc.',
    )
    reviewTime: Optional[str] = Field(
        None, description='Unix timestamp (in seconds) of the review, in UTC+0.'
    )
    title: Optional[str] = Field(
        None, description='The title of the review, for example: Great three bedrooms.'
    )
    type: Optional[Type1] = Field(None, description='The type of the review.')
    visitTime: Optional[str] = Field(
        None, description='Unix timestamp (in seconds) of when the stay was, in UTC+0.'
    )


class SetLiveOnGoogleRequest(BaseModel):
    liveOnGoogle: Optional[bool] = Field(
        None,
        description='Required. Whether the property will show on Google. When true, Google will show the properties if their integration is complete and the property is available. When false, Google will never show the properties.',
    )
    partnerHotelIds: Optional[List[str]] = Field(
        None,
        description='Required. Identifies the properties to update with the liveOnGoogle setting.',
    )


class SetLiveOnGoogleResponse(BaseModel):
    failedHotelIds: Optional[List[str]] = Field(
        None, description='Identifies properties that Google could not update.'
    )
    updatedHotelIds: Optional[List[str]] = Field(
        None, description='Identifies the updated properties.'
    )


class SummarizeHotelViewsResponse(BaseModel):
    lastFeedSubmissionTime: Optional[str] = Field(
        None, description='Timestamp of the last hotel feed submission.'
    )
    lastManifestUpdateTime: Optional[str] = Field(
        None, description='Timestamp of the last hotel manifest update.'
    )
    liveOnGooglePropertyCount: Optional[str] = Field(
        None, description='The number of properties that are Live on Google.'
    )
    matchedPropertyCount: Optional[str] = Field(
        None, description="The number of properties that match Google's manifest."
    )
    overclusteredPropertyCount: Optional[str] = Field(
        None, description='The number of hotels that are considered overclustered.'
    )
    overclusteredPropertyWithErrorsCount: Optional[str] = Field(
        None,
        description='The number of overclustered properties that have data-related errors.',
    )
    unmatchedPropertyCount: Optional[str] = Field(
        None, description='The number of properties that are considered unmatched.'
    )
    unmatchedPropertyWithErrorsCount: Optional[str] = Field(
        None,
        description='The number of unmatched properties that have data-related errors.',
    )


class CurrentBookOnGoogleScore(Enum):
    PRICE_ACCURACY_STATE_UNSPECIFIED = 'PRICE_ACCURACY_STATE_UNSPECIFIED'
    PRICE_ACCURACY_STATE_UNKNOWN = 'PRICE_ACCURACY_STATE_UNKNOWN'
    EXCELLENT = 'EXCELLENT'
    GOOD = 'GOOD'
    POOR = 'POOR'
    AT_RISK = 'AT_RISK'
    FAILED = 'FAILED'


class CurrentOverallScore(Enum):
    PRICE_ACCURACY_STATE_UNSPECIFIED = 'PRICE_ACCURACY_STATE_UNSPECIFIED'
    PRICE_ACCURACY_STATE_UNKNOWN = 'PRICE_ACCURACY_STATE_UNKNOWN'
    EXCELLENT = 'EXCELLENT'
    GOOD = 'GOOD'
    POOR = 'POOR'
    AT_RISK = 'AT_RISK'
    FAILED = 'FAILED'


class CurrentScore(Enum):
    PRICE_ACCURACY_STATE_UNSPECIFIED = 'PRICE_ACCURACY_STATE_UNSPECIFIED'
    PRICE_ACCURACY_STATE_UNKNOWN = 'PRICE_ACCURACY_STATE_UNKNOWN'
    EXCELLENT = 'EXCELLENT'
    GOOD = 'GOOD'
    POOR = 'POOR'
    AT_RISK = 'AT_RISK'
    FAILED = 'FAILED'


class CurrentWebsiteScore(Enum):
    PRICE_ACCURACY_STATE_UNSPECIFIED = 'PRICE_ACCURACY_STATE_UNSPECIFIED'
    PRICE_ACCURACY_STATE_UNKNOWN = 'PRICE_ACCURACY_STATE_UNKNOWN'
    EXCELLENT = 'EXCELLENT'
    GOOD = 'GOOD'
    POOR = 'POOR'
    AT_RISK = 'AT_RISK'
    FAILED = 'FAILED'


class PredictedBookOnGoogleScore(Enum):
    PRICE_ACCURACY_STATE_UNSPECIFIED = 'PRICE_ACCURACY_STATE_UNSPECIFIED'
    PRICE_ACCURACY_STATE_UNKNOWN = 'PRICE_ACCURACY_STATE_UNKNOWN'
    EXCELLENT = 'EXCELLENT'
    GOOD = 'GOOD'
    POOR = 'POOR'
    AT_RISK = 'AT_RISK'
    FAILED = 'FAILED'


class PredictedOverallScore(Enum):
    PRICE_ACCURACY_STATE_UNSPECIFIED = 'PRICE_ACCURACY_STATE_UNSPECIFIED'
    PRICE_ACCURACY_STATE_UNKNOWN = 'PRICE_ACCURACY_STATE_UNKNOWN'
    EXCELLENT = 'EXCELLENT'
    GOOD = 'GOOD'
    POOR = 'POOR'
    AT_RISK = 'AT_RISK'
    FAILED = 'FAILED'


class PredictedScore(Enum):
    PRICE_ACCURACY_STATE_UNSPECIFIED = 'PRICE_ACCURACY_STATE_UNSPECIFIED'
    PRICE_ACCURACY_STATE_UNKNOWN = 'PRICE_ACCURACY_STATE_UNKNOWN'
    EXCELLENT = 'EXCELLENT'
    GOOD = 'GOOD'
    POOR = 'POOR'
    AT_RISK = 'AT_RISK'
    FAILED = 'FAILED'


class PredictedWebsiteScore(Enum):
    PRICE_ACCURACY_STATE_UNSPECIFIED = 'PRICE_ACCURACY_STATE_UNSPECIFIED'
    PRICE_ACCURACY_STATE_UNKNOWN = 'PRICE_ACCURACY_STATE_UNKNOWN'
    EXCELLENT = 'EXCELLENT'
    GOOD = 'GOOD'
    POOR = 'POOR'
    AT_RISK = 'AT_RISK'
    FAILED = 'FAILED'


class SummarizePriceAccuracyResponse(BaseModel):
    currentBookOnGoogleScore: Optional[CurrentBookOnGoogleScore] = Field(
        None, description='The current Book on Google price accuracy score.'
    )
    currentOverallScore: Optional[CurrentOverallScore] = Field(
        None,
        description='The current price accuracy score combining both website and Book on Google scores.',
    )
    currentScore: Optional[CurrentScore] = Field(
        None,
        description="The current price accuracy score. Contains the same value as `current_website_score`. For clarity, use either `current_website_score` or 'current_overall_score` depending upon which is needed.",
    )
    currentWebsiteScore: Optional[CurrentWebsiteScore] = Field(
        None, description='The current website price accuracy score.'
    )
    predictedBookOnGoogleScore: Optional[PredictedBookOnGoogleScore] = Field(
        None, description='The predicted Book on Google price accuracy score.'
    )
    predictedOverallScore: Optional[PredictedOverallScore] = Field(
        None,
        description='The predicted price accuracy score combining both website and Book on Google scores.',
    )
    predictedScore: Optional[PredictedScore] = Field(
        None,
        description="The predicted price accuracy score. Contains the same value as `predicted_website_score`. For clarity, use either `predicted_website_score` or 'predicted_overall_score` depending upon which is needed.",
    )
    predictedWebsiteScore: Optional[PredictedWebsiteScore] = Field(
        None, description='The predicted website price accuracy score.'
    )
    updateTime: Optional[str] = Field(
        None, description='The update timestamp for the current score.'
    )


class ValidateReconciliationReportResponse(BaseModel):
    issues: Optional[List[ReconciliationReportValidationIssue]] = Field(
        None, description='Issues that were encountered when validating the file.'
    )
    successfulRecordCount: Optional[int] = Field(
        None,
        description='The number of commission records that were successfully validated.',
    )


class VerifyListingsRequest(BaseModel):
    xmlListing: Optional[str] = Field(
        None,
        description='A listing that follows the XML format specified in https://developers.google.com/hotels/hotel-prices/xml-reference/hotel-list-feed.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class AccountLinkTarget(BaseModel):
    allHotels: Optional[bool] = Field(
        None,
        description='True if all properties under the Hotel Center account are made available to the account link. The default is `false`.',
    )
    hotelList: Optional[HotelList] = Field(
        None,
        description='List of properties that is made available to the account link.',
    )


class Brand(BaseModel):
    activeDisplayNames: Optional[List[LocalizedText]] = Field(
        None,
        description="Output only. The brand's active display names in all provided languages, only present if the display name is approved for all provided languages.",
    )
    activeIcon: Optional[str] = Field(
        None,
        description="Output only. The brand's active [accounts.icon](/hotels/hotel-prices/api-reference/rest/v3/accounts.icons#resource:-iconresource). The value refers to the icons's resource name in the format `accounts/{account_id}/icons/{icon_id}`. An active icon is one that has been approved.",
    )
    activeIconUri: Optional[str] = Field(
        None,
        description='Output only. URL of the active icon, only present when the icon has been approved.',
    )
    displayNameDisapprovalReason: Optional[List[DisplayNameDisapprovalReason]] = Field(
        None,
        description="Output only. Display name's disapproval reason. Only applies to display names with the review state 'REJECTED'.",
    )
    displayNameState: Optional[DisplayNameState] = Field(
        None,
        description="Output only. The brand's display names review state, which applies to all display name language entries. If there are both submitted and active display names, this refers to the submitted display names.",
    )
    displayNames: Optional[List[LocalizedText]] = Field(
        None,
        description="Input only. The name Google displays for the brand's properties. Setting the display names is only necessary if you want to override the landing page display name or account-level display name for the brand. Google reviews the display names for appropriate content. When there are multiple languages, Google will only show the display names once Google approves all the languages.",
    )
    icon: Optional[str] = Field(
        None,
        description="Input only. The brand's [accounts.icon](/hotels/hotel-prices/api-reference/rest/v3/accounts.icons#resource:-iconresource) identifying the brand's icon. The value refers to the icons's resource name in the format `accounts/{account_id}/icons/{icon_id}`.",
    )
    iconDisapprovalReasons: Optional[List[IconDisapprovalReason]] = Field(
        None,
        description="Output only. The icon's disapproval reason(s). Only applies to submitted icons with `REJECTED` state.",
    )
    iconState: Optional[IconState] = Field(
        None,
        description="Output only. The brand's icon's review state. If there are both submitted and active icons, this refers to the submitted icon.",
    )
    name: Optional[str] = Field(
        None,
        description="Output only. The resource name for the brand in the format `accounts/{account_id}/brands/{brand_id}`. The `brand_id` corresponds to the partner's brand identifier used for landing page matching and the property-level brand identifier. A default brand is applied to properties that do not have a brand. The `brand_id` of the default brand is `NO_BRAND_ID`. It can be fetched and updated like any configured brand.",
    )
    propertyCount: Optional[str] = Field(
        None,
        description='Output only. The number of properties with the corresponding brand ID.',
    )
    submittedDisplayNames: Optional[List[LocalizedText]] = Field(
        None,
        description="Output only. The brand's submitted display names in all provided languages, only present if the display name is new or rejected for any language.",
    )
    submittedIcon: Optional[str] = Field(
        None,
        description="Output only. The brand's submitted [accounts.icon](/hotels/hotel-prices/api-reference/rest/v3/accounts.icons#resource:-iconresource). The value refers to the icons's resource name in the format `accounts/{account_id}/icons/{icon_id}`. A submitted icon is one that is new or rejected.",
    )


class CreateReconciliationReportResponse(BaseModel):
    issues: Optional[List[ReconciliationReportValidationIssue]] = Field(
        None, description='Issues that were encountered when validating the file.'
    )
    reconciliationReport: Optional[ReconciliationReport] = Field(
        None,
        description='Resource name of the new reconciliation report. The format is `accounts/{account_id}`.',
    )
    successfulRecordCount: Optional[int] = Field(
        None,
        description='The number of commission records that were successfully saved.',
    )


class Image(BaseModel):
    galleryUri: Optional[List[LocalizedText]] = Field(
        None,
        description='URL that is deeplink to the image in a gallery (or a webpage).',
    )
    title: Optional[List[LocalizedText]] = Field(
        None, description='Title of the image.'
    )
    uri: Optional[str] = Field(
        None, description='URL that points to the binary image content directly.'
    )


class ListBrandsResponse(BaseModel):
    brands: Optional[List[Brand]] = Field(
        None,
        description='A list of all brands associated with the Hotel Center account being queried.',
    )


class ListPriceCoverageViewsResponse(BaseModel):
    priceCoverageViews: Optional[List[PriceCoverageView]] = Field(
        None, description='Hotel price coverage stats.'
    )


class ListReconciliationReportsResponse(BaseModel):
    reconciliationReports: Optional[List[ReconciliationReport]] = Field(
        None,
        description='The list of names of reconciliation reports. Note that the `contents` and `fileName` fields of each `ReconciliationReport` object are not returned by this call.',
    )


class MissedParticipationCountDetails(BaseModel):
    hotelSuspendedCount: Optional[str] = Field(
        None,
        description='The total number of missed participations due to one or more of your hotels being suspended due to price accuracy violations.',
    )
    noAvailabilityCount: Optional[str] = Field(
        None,
        description='The total number of missed participation due to the hotel/itinerary combination being unavailable, or the traveler was ineligible for the rates. To participate in these auctions, you may need to provide more pricing information.',
    )
    noLandingPageCount: Optional[str] = Field(
        None, description='No landing page matched the user.'
    )
    noPriceCount: Optional[str] = Field(
        None,
        description='The total number of missed participations due to a price not being offered for the requested itinerary.',
    )
    noPriceCountDetails: Optional[NoPriceCountDetails] = Field(
        None,
        description='The reasons that contributed to the no price count (for example, live pricing not available) and the total count for each reason.',
    )
    noTaxBreakdownCount: Optional[str] = Field(
        None,
        description='The total number of missed participation due to one or more of your hotels not specifying taxes and fees separately.',
    )
    otherReasonCount: Optional[str] = Field(
        None, description='Hotel did not participate for an unknown reason.'
    )
    priceMissingCount: Optional[str] = Field(
        None,
        description="The total number of missed participations due to either a price not being present in Google's cache or failing to successfully respond to live pricing. Comprised of the following: * Bandwidth depleted * Cache rate missing * Itinerary blocked * Live pricing not set up * Live pricing timeout * Live pricing error",
    )
    priceMissingCountDetails: Optional[PriceMissingCountDetails] = Field(
        None, description='The reasons that contributed to the price missing count.'
    )
    priceProblemCount: Optional[str] = Field(
        None,
        description='The total number of missed participation due to an issue with the accuracy of the price provided for the itinerary. Comprised of the following: * Hotel suspended * Price unusually high * Price unusually low * Taxes and feeds missing',
    )
    priceProblemCountDetails: Optional[PriceProblemCountDetails] = Field(
        None, description='The reasons that contributed to the price problem count.'
    )
    priceUnavailableCount: Optional[str] = Field(
        None,
        description='The total number of missed participation due to price listed as unavailable (-1) for the requested itinerary. Comprised of the following: * Price unavailable * Participation not likely * Other',
    )
    priceUnavailableCountDetails: Optional[PriceUnavailableCountDetails] = Field(
        None, description='The reasons that contributed to the price unavailable count.'
    )


class ParsedListing(BaseModel):
    brand: Optional[str] = Field(
        None,
        description='If not empty, it indicates that this listing belongs to a brand of the feed.',
    )
    category: Optional[List[LocalizedText]] = Field(
        None,
        description='The partner provided category (accommodation type) of the property.',
    )
    dataIssueDetail: Optional[List[DataIssueDetail]] = Field(
        None, description='Data issues about this listing'
    )
    description: Optional[List[LocalizedText]] = Field(
        None, description='Description of the property.'
    )
    image: Optional[List[Image]] = Field(
        None, description='Images associated with this listing, localized.'
    )
    imprecisionRadiusMeters: Optional[int] = Field(
        None,
        description='Represents the accuracy of the location. The listing can be anywhere within the defined circular area.',
    )
    isServed: Optional[bool] = Field(
        None,
        description='Whether the listing can be served based on non image data alone.',
    )
    listingName: Optional[List[LocalizedText]] = Field(
        None, description='List of localized names.'
    )
    location: Optional[LatLng] = Field(
        None, description='Location of listing in lat/lng (degrees).'
    )
    partnerListId: Optional[str] = Field(
        None, description='The list id on partner lec feed, provided by partner.'
    )
    regionCode: Optional[str] = Field(
        None, description='The country code where the listing is located.'
    )
    review: Optional[List[Review]] = Field(
        None,
        description='Reviews associated with this listing. Each review proto has a single language attached to it.',
    )
    unitAttributes: Optional[Dict[str, str]] = Field(
        None, description='VR List attribute.'
    )


class ParticipationResult(BaseModel):
    key: Optional[Key] = Field(None, description='Key of the result.')
    missedParticipationCount: Optional[str] = Field(
        None,
        description='The total number of opportunities **not** eligible for the Google Ads auction process. Comprised of the following: * Landing page missing * Price missing * Price problem * Price unavailable * Other',
    )
    missedParticipationCountDetails: Optional[MissedParticipationCountDetails] = Field(
        None,
        description='The reasons that contributed to the missed participation count (for example, no availability) and a total count for each reason.',
    )
    opportunityCount: Optional[str] = Field(
        None,
        description='For a specific hotel, the total number of opportunities that were available. Opportunities are the total number of instances when a hotel ad could have been displayed to a user.',
    )
    participationCount: Optional[str] = Field(
        None,
        description='The total number of opportunities for which you were eligible to enter in the Google Ads auction process.',
    )
    participationPercent: Optional[float] = Field(
        None,
        description='The percentage rate of participation where the number of successfully participated opportunities is divided by the total number of opportunities. For example, if a property was eligible to enter the Google Ads auction 90 times out of 100 opportunities, the participation rate is 90%.',
    )
    partnerHotelDisplayName: Optional[str] = Field(
        None,
        description="Partner's hotel display name. This field is only populated when the result is aggregated by `partnerHotelId`.",
    )


class PriceAccuracyRow(BaseModel):
    adultOccupancy: Optional[int] = Field(
        None,
        description='The number of adults in the occupancy details of the validation query.',
    )
    affectsScore: Optional[bool] = Field(
        None,
        description='True if this row affects the placement of a price. This field has been renamed to “Affects placement” in Hotel Center.',
    )
    cachedPriceRecord: Optional[PriceRecord] = Field(
        None, description='Price as advertised.'
    )
    checkinDate: Optional[Date] = Field(None, description='Check-in date.')
    childOccupancy: Optional[int] = Field(
        None,
        description='The number of children in the occupancy details of the validation query.',
    )
    correctionTime: Optional[str] = Field(
        None,
        description='Time at which an incorrect price is updated to a correct price.',
    )
    deviceType: Optional[DeviceType] = Field(
        None, description="The user's device type."
    )
    fetchedPriceRecord: Optional[PriceRecord] = Field(
        None, description='Price as read from the partner website.'
    )
    finalDomain: Optional[str] = Field(
        None, description='The domain of the final page from which prices are read.'
    )
    hotel: Optional[str] = Field(None, description='Partner-defined hotel ID.')
    hotelCountryCode: Optional[str] = Field(
        None, description='The country of the hotel (based on address).'
    )
    lengthOfStayDays: Optional[int] = Field(None, description='Length of stay.')
    mismatchReason: Optional[MismatchReason] = Field(
        None,
        description="The reason why the fetched price didn't match the cached price.",
    )
    rateRuleId: Optional[str] = Field(
        None, description='The rate rule of the advertised price for non-public rates.'
    )
    signalSource: Optional[SignalSource] = Field(
        None, description='Source of the price accuracy signal.'
    )
    url: Optional[str] = Field(
        None, description='Initial URL visited on the partner website.'
    )
    userRegionCode: Optional[str] = Field(None, description="The user's region.")


class PriceAccuracyView(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Resource name should be in the format `accounts/{account_id}/priceAccuracyViews/{report_date}`.',
    )
    results: Optional[List[PriceAccuracyRow]] = Field(
        None, description='The list of rows that match the query.'
    )


class QueryParticipationReportResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Pagination token used to retrieve the next page of results.'
    )
    results: Optional[List[ParticipationResult]] = Field(
        None, description='The list of results that matches the query.'
    )


class VerifyListingsResponse(BaseModel):
    parsedListing: Optional[ParsedListing] = Field(
        None, description='The parsed listing output.'
    )


class AccountLink(BaseModel):
    accountLinkTarget: Optional[AccountLinkTarget] = Field(
        None,
        description='Required for CREATE requests. The properties in the Hotel Center account that can be managed using the linked Google Ads account.',
    )
    googleAdsCustomerName: Optional[str] = Field(
        None,
        description='Required for CREATE requests. The value representing the Google Ads customer ID in the format `customers/{google_ads_customer_id}`. For example: `customers/0123456789`. Note that the `googleAdsCustomerName` field is not returned in responses to GET requests.',
    )
    name: Optional[str] = Field(
        None,
        description='The resource name for the account link in the format `accounts/{account_id}/accountLinks/{account_link_id}`.',
    )
    status: Optional[Status] = Field(
        None, description='The current status of the account link.'
    )


class ListAccountLinksResponse(BaseModel):
    accountLinks: Optional[List[AccountLink]] = Field(
        None,
        description='A list of all account links associated with the Hotel Center account being queried.',
    )


class ListPriceAccuracyViewsResponse(BaseModel):
    priceAccuracyViews: Optional[List[PriceAccuracyView]] = Field(
        None, description='The list of rows that match the query.'
    )
